export default {
  products:[
      {
         _id:'1',
         name:'Fing Shirts',
         Category:'Shirts',
         image:'/images/product-1.jpg',
         price:60,
         bradnd:'Hiskywain',
         rating:4.5,
         numReviews:10,
         countInStock:6,
      },
      {
        _id:'2',
        name:'nning Shirts',
        Category:'Shirts',
        image:'/images/product-2.jpg',
        price:50,
        bradnd:'Nike',
        rating:4.0,
        numReviews:20,
        countInStock:8,
     },
     {
        _id:'3',
        name:' Shits',
        Category:'Shirts',
        image:'/images/product-3.jpg',
        price:30,
        bradnd:'Puma',
        rating:3.5,
        numReviews:10,
        countInStock:6,
     },
     {
        _id:'4',
        name:' Running Shirts',
        Category:'Shirts',
        image:'/images/product-4.jpg',
        price:40,
        bradnd:'Hiskywain',
        rating:3.5,
        numReviews:50,
        countInStock:9,
     },
     {
        _id:'5',
        name:'Full b Shirts',
        Category:'Shirts',
        image:'/images/product-5.jpg',
        price:50,
        bradnd:'Addidas',
        rating:3.5,
        numReviews:100,
        countInStock:16,
     },
     {
        _id: '6',
        name: 'Best Pants',
        category: 'Pants',
        image: '/images/product-6.jpg',
        price: 66,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock:50,
      },
  ] , 
};